config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :clients, :makers, :articles, :client_articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one :old_article, class_name: 'Article', foreign_key: "new_article_id"
  belongs_to :new_article, class_name: 'Article', foreign_key: "new_article_id", optional: true
  belongs_to :maker
  has_many :client_articles

  validates :unit_buy_cost, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_buy_cost, :maker_reference, :description, :maker_id, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :client_articles

  validates :name, presence: true
end

app/models/client_article.rb
class ClientArticle < ApplicationRecord
  belongs_to :article
  belongs_to :client

  validates :article_code, :unit_sell_cost, :validity, :article_id, :client_id, presence: true
  validates :unit_sell_cost, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_buy_cost, numericality: { only_integer: true, greater_than: 0, allow_nil: true }
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :articles

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
  end

  def create
  end

  def show
    @article = Article.find(params[:id])
    @client_articles = @article.client_articles.sort_by(&:validity)
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/client_articles_controller.rb
class ClientArticlesController < ApplicationController
  def index
    @client_articles = ClientArticle.all.sort_by(&:validity)
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def new
  end

  def create
  end

  def show
    @client = Client.find(params[:id])
    @articles = @client.client_articles.sort_by(&:validity)
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  def index
    @makers = Maker.all
  end

  def new
  end

  def create
  end

  def show
    @maker = Maker.find(params[:id])
    @articles = @maker.articles
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_card_article.html.erb
<div class="card-article <%= "obsolete" if article.obsolete %>">
  <div class="card-line">
    <p class="reference"><%= article.maker_reference %></p>
    <p class="maker"><%= article.maker.name %></p>
  </div>
  <div class="card-line">
    <p class="description"><%= article.short_description.nil? ? article.description : article.short_description %></p>
  </div>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<div class="container">
  <h1 class="text-center mb-5 mt-2">Articles</h1>
  <% @articles.each do |article| %>
    <%= link_to article_path(article), class: "text-reset text-decoration-none" do %>
      <%= render  "articles/card_article", article: article %>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<div class="container">
  <div class="article-data">
    <h1><%= @article.maker_reference%></h1>
    <div class="data">
      <h2>Fabricant:</h2>
      <p><%= @article.maker.name %></p>
    </div>
    <div class="data">
      <h2>Prix d'achat:</h2>
      <p><%= @article.unit_buy_cost.fdiv(100).round(2) %></p>
    </div>
    <div class="data">
      <h2>Contrat:</h2>
      <i class="fas <%= @article.contracted ? "fa-check" : "fa-times" %>"></i>
    </div>
    <div class="data">
      <h2>Obsolete:</h2>
      <i class="fas <%= @article.obsolete ? "fa-check" : "fa-times" %>"></i>
    </div>
    <% if @article.obsolete %>
      <div class="data">
        <h2>Remplacement:</h2>
        <%= link_to  @article.new_article.maker_reference, article_path(@article.new_article) %>
      </div>
    <% end %>

    <div class="description">
      <h2>Description longue:</h2>
      <p><%= @article.description.nil? ? "pas de description" : @article.description %></p>
    <div class="description">
      <h2>Description courte:</h2>
      <p><%= @article.short_description.nil? ? "pas de description courte" : @article.short_description %></p>
    </div>
    <div class="description">
      <h2>Commentaire</h2>
      <p><%= @article.comment.nil? ? "pas de commentaire" : @article.comment %></p>
    </div>
  </div>
</div>
  <% unless @client_articles.count.zero? %>
    <div>
      <h2 class="mt-5 text-center">Articles client:</h2>
        <% @client_articles.each do |article| %>
          <%= link_to client_article_path(article), class: "text-reset text-decoration-none" do %>
            <%= render  "client_articles/card_client_article", article: article %>
          <% end %>
        <% end %>
    </div>
  <% end %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/client_articles/_card_client_article.html.erb
<div class="card-article">
  <div class="card-line">
    <p class="reference"><%= article.article_code %></p>
    <p class="maker"><%= article.client.name %></p>
  </div>
  <div class="card-line">
    <p>ref: <%= article.article.maker_reference %></p>
    <p>prix de vente: <%= article.unit_sell_cost.fdiv(100).round(2) %></p>
    <p>prix d'achat: <%= (article.unit_buy_cost.nil? ? article.article.unit_buy_cost : article.unit_buy_cost).fdiv(100).round(2) %></p>
  </div>
  <div class="card-line">
    <p>DDP: <%= article.DDP.nil? ? "-" : article.DDP %></p>
    <p class="<%= Time.now > article.validity ? "invalid" : "valid" %>">Validité: <%= article.validity.strftime("%d/%m/%Y") %></p>
  </div>
</div>

app/views/client_articles/create.html.erb
<h1>ClientArticles#create</h1>
<p>Find me in app/views/client_articles/create.html.erb</p>

app/views/client_articles/destroy.html.erb
<h1>ClientArticles#destroy</h1>
<p>Find me in app/views/client_articles/destroy.html.erb</p>

app/views/client_articles/edit.html.erb
<h1>ClientArticles#edit</h1>
<p>Find me in app/views/client_articles/edit.html.erb</p>

app/views/client_articles/index.html.erb
<div class="container">
  <h1 class="text-center mb-5 mt-2">Articles client</h1>
  <% @client_articles.each do |article| %>
    <%= link_to article_path(article.article), class: "text-reset text-decoration-none" do %>
      <%= render  "client_articles/card_client_article", article: article %>
    <% end %>
  <% end %>
</div>

app/views/client_articles/new.html.erb
<h1>ClientArticles#new</h1>
<p>Find me in app/views/client_articles/new.html.erb</p>

app/views/client_articles/show.html.erb
<h1>ClientArticles#show</h1>
<p>Find me in app/views/client_articles/show.html.erb</p>

app/views/client_articles/update.html.erb
<h1>ClientArticles#update</h1>
<p>Find me in app/views/client_articles/update.html.erb</p>

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<h1>Clients#edit</h1>
<p>Find me in app/views/clients/edit.html.erb</p>

app/views/clients/index.html.erb
<div class="container">
  <h1 class="text-center">Clients</h1>
  <div class="makers-list">
    <% @clients.each do |client| %>
      <%= link_to  client.name, client_path(client) %>
    <% end %>
  </div>
</div>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<div class="container">
  <h1 class="text-center m-5"><%= @client.name %></h1>
  <h2 class="text-center">articles:</h2>
  <% @articles.each do |article| %>
    <%= link_to article_path(article.article), class: "text-reset text-decoration-none" do %>
      <%= render  "client_articles/card_client_article", article: article %>
    <% end %>
  <% end %>
</div>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render  "pages/header" %>
    <%= yield %>
  </body>
</html>

app/views/makers/create.html.erb
<h1>Makers#create</h1>
<p>Find me in app/views/makers/create.html.erb</p>

app/views/makers/destroy.html.erb
<h1>Makers#destroy</h1>
<p>Find me in app/views/makers/destroy.html.erb</p>

app/views/makers/edit.html.erb
<h1>Makers#edit</h1>
<p>Find me in app/views/makers/edit.html.erb</p>

app/views/makers/index.html.erb
<div class="container">
  <h1 class="text-center">Fabricants</h1>
  <div class="makers-list">
    <% @makers.each do |maker| %>
      <%= link_to  maker.name, maker_path(maker) %>
    <% end %>
  </div>
</div>

app/views/makers/new.html.erb
<h1>Makers#new</h1>
<p>Find me in app/views/makers/new.html.erb</p>

app/views/makers/show.html.erb
<div class="container">
  <h1 class="text-center m-5"><%= @maker.name %></h1>
  <h2 class="text-center">articles:</h2>
  <% @articles.each do |article| %>
    <%= link_to article_path(article), class: "text-reset text-decoration-none" do %>
      <%= render  "articles/card_article", article: article %>
    <% end %>
  <% end %>
</div>

app/views/makers/update.html.erb
<h1>Makers#update</h1>
<p>Find me in app/views/makers/update.html.erb</p>

app/views/pages/_header.html.erb
<header>
  <div class="header">
    <%= link_to  "Articles", articles_path %>
    <%= link_to "Articles client", client_articles_path %>
    <%= link_to  "Fabricants", makers_path %>
    <%= link_to  "Clients", clients_path %>
  </div>
</header>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>